// spellchecker:disable
export const cssNamedColors = [
  "indianred",
  "lightcoral",
  "salmon",
  "darksalmon",
  "lightsalmon",
  "crimson",
  "red",
  "firebrick",
  "darkred",
  "pink",
  "lightpink",
  "hotpink",
  "deeppink",
  "mediumvioletred",
  "palevioletred",
  "coral",
  "tomato",
  "orangered",
  "darkorange",
  "orange",
  "gold",
  "yellow",
  "lightyellow",
  "lemonchiffon",
  "lightgoldenrodyellow",
  "papayawhip",
  "moccasin",
  "peachpuff",
  "palegoldenrod",
  "khaki",
  "darkkhaki",
  "lavender",
  "thistle",
  "plum",
  "violet",
  "orchid",
  "fuchsia",
  "magenta",
  "mediumorchid",
  "mediumpurple",
  "blueviolet",
  "darkviolet",
  "darkorchid",
  "darkmagenta",
  "purple",
  "rebeccapurple",
  "indigo",
  "mediumslateblue",
  "slateblue",
  "darkslateblue",
  "greenyellow",
  "chartreuse",
  "lawngreen",
  "lime",
  "limegreen",
  "palegreen",
  "lightgreen",
  "mediumspringgreen",
  "springgreen",
  "mediumseagreen",
  "seagreen",
  "forestgreen",
  "green",
  "darkgreen",
  "yellowgreen",
  "olivedrab",
  "olive",
  "darkolivegreen",
  "mediumaquamarine",
  "darkseagreen",
  "lightseagreen",
  "darkcyan",
  "teal",
  "aqua",
  "cyan",
  "lightcyan",
  "paleturquoise",
  "aquamarine",
  "turquoise",
  "mediumturquoise",
  "darkturquoise",
  "cadetblue",
  "steelblue",
  "lightsteelblue",
  "powderblue",
  "lightblue",
  "skyblue",
  "lightskyblue",
  "deepskyblue",
  "dodgerblue",
  "cornflowerblue",
  "royalblue",
  "blue",
  "mediumblue",
  "darkblue",
  "navy",
  "midnightblue",
  "cornsilk",
  "blanchedalmond",
  "bisque",
  "navajowhite",
  "wheat",
  "burlywood",
  "tan",
  "rosybrown",
  "sandybrown",
  "goldenrod",
  "darkgoldenrod",
  "peru",
  "chocolate",
  "saddlebrown",
  "sienna",
  "brown",
  "maroon",
  "white",
  "snow",
  "honeydew",
  "mintcream",
  "azure",
  "aliceblue",
  "ghostwhite",
  "whitesmoke",
  "seashell",
  "beige",
  "oldlace",
  "floralwhite",
  "ivory",
  "antiquewhite",
  "linen",
  "lavenderblush",
  "mistyrose",
  "gainsboro",
  "lightgray",
  "lightgrey",
  "silver",
  "darkgray",
  "darkgrey",
  "gray",
  "grey",
  "dimgray",
  "dimgrey",
  "lightslategray",
  "lightslategrey",
  "slategray",
  "slategrey",
  "darkslategray",
  "darkslategrey",
  "black",
  "transparent",
  "currentColor",
];
// spellchecker:enable

// RGB[A] hexa: #123456AA, #B4DA55, #000A, #123
const hexRGBA = String.raw`\#(([0-9A-Fa-f]{8})|([0-9A-Fa-f]{6})|([0-9A-Fa-f]{4})|([0-9A-Fa-f]{3}))`;

// RGB 0-255: rgb(10,20,30)
const RGBIntegers = String.raw`rgb\(\d{1,3}\,\d{1,3}\,\d{1,3}\)`;

// RGB %: rgb(25%,50%,75%)
const RGBPercentages = String.raw`rgb\(\d{1,3}%\,\d{1,3}%\,\d{1,3}%\)`;

// RGBA: rgba(50,100,255,.5), rgba(50,100,255,50%)
const supportedRGBA = String.raw`rgba\(\d{1,3}\,\d{1,3}\,\d{1,3}\,\d*(\.\d*)?%?\)`;

export const RGBAPercentages = String.raw`rgba\(\d{1,3}%\,\d{1,3}%\,\d{1,3}%\,\d*(\.\d*)?%?\)`;

export const optionalColorPrefixedVar = String.raw`(color\:)?var\(\-\-[A-Za-z\-]{1,}\)`;

export const mandatoryColorPrefixed = String.raw`color\:(?!(hsla\()).{1,}`;

export const notHSLAPlusWildcard = String.raw`(?!(hsla\()).{1,}`;

// HSL
const supportedHSL = String.raw`hsl\(\d{1,3}%?\,\d{1,3}%?\,\d{1,3}%?\)`;

export const colorValues = [
  hexRGBA,
  RGBIntegers,
  RGBPercentages,
  supportedRGBA,
  supportedHSL,
];

export const mergedColorValues = [...cssNamedColors, ...colorValues];
